access_token = "sbp_0889a1bf40eecf7f14879b05a4dc658838c26d83"
project_id = "pwjunnsldyqhfrjxxvub"
project_url = "https://pwjunnsldyqhfrjxxvub.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3anVubnNsZHlxaGZyanh4dnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjMxNzcsImV4cCI6MjA2NzYzOTE3N30.H2moTjJM60FVffF-uK8c9MNaVpkymuXH8Up1JYKnTn4"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3anVubnNsZHlxaGZyanh4dnViIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjA2MzE3NywiZXhwIjoyMDY3NjM5MTc3fQ.Frs491DoCC0QeHCTj8l8SwciyRjXWt7i7NjikZGHWAQ"
