[build]
builder = "DOCKERFILE"
dockerfilePath = "../Dockerfile.frontend"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 